#!/usr/bin/env bash
# scripts/ai/generate_daily_report.sh
# Purpose: build / drift / marketing の結果を収集し、OpenRouter 経由で daily report を生成する。
# Usage: bash scripts/ai/generate_daily_report.sh
# Env: OPENROUTER_API_KEY (required), GITHUB_TOKEN (optional, for PR creation)
# Output: docs/reports/daily/YYYY-MM-DD.md

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATE=$(date -u +"%Y-%m-%d")
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
REPORT_PATH="${REPO_ROOT}/docs/reports/daily/${DATE}.md"

# --- 依存チェック ---
if [ -z "${OPENROUTER_API_KEY:-}" ]; then
  echo "ERROR: OPENROUTER_API_KEY が未設定です。"
  echo "export OPENROUTER_API_KEY=sk-or-v1-..." 
  exit 1
fi

echo "=== Daily Report Generator — ${TIMESTAMP} ==="
echo ""

# --- sub-scripts を実行してコンテキストを収集 ---
BUILD_RESULT=""
DRIFT_RESULT=""
MARKETING_RESULT=""

echo "1. Running build check..."
if bash "${REPO_ROOT}/scripts/ai/run_build_checks.sh" > /tmp/build_output.md 2>&1; then
  BUILD_RESULT=$(cat /tmp/build_output.md)
  echo "   done."
else
  BUILD_RESULT="(build check script failed to run)"
fi

echo "2. Running drift check..."
if bash "${REPO_ROOT}/scripts/ai/detect_architecture_drift.sh" > /tmp/drift_output.md 2>&1; then
  DRIFT_RESULT=$(cat /tmp/drift_output.md)
  echo "   done."
else
  DRIFT_RESULT="(drift check script failed to run)"
fi

echo "3. Running marketing health check..."
if bash "${REPO_ROOT}/scripts/ai/detect_marketing_health.sh" > /tmp/marketing_output.md 2>&1; then
  MARKETING_RESULT=$(cat /tmp/marketing_output.md)
  echo "   done."
else
  MARKETING_RESULT="(marketing health script failed to run)"
fi

# --- Open Loops の High 優先度を抽出 ---
OPEN_HIGH=""
if [ -f "${REPO_ROOT}/OPEN_LOOPS.md" ]; then
  OPEN_HIGH=$(grep -A2 "| High" "${REPO_ROOT}/OPEN_LOOPS.md" 2>/dev/null | head -20 || echo "OPEN_LOOPS.md に High 優先度なし")
fi

# --- OpenRouter で report 生成 ---
echo "4. Calling OpenRouter API..."

SYSTEM_PROMPT="あなたは Give Me a DAY プロジェクトの Docs / Knowledge Agent です。
以下のルールに従って daily report を生成してください。
- 推測を事実として書かない。事実がなければ UNKNOWN と書く
- build / drift / marketing の3項目を必ず埋める
- 箇条書きで簡潔に
- 日本語で書く
- 出力は markdown のみ（前置き不要）"

USER_PROMPT="以下の情報を使って、${DATE} の daily report を生成してください。

# Build Check 結果
${BUILD_RESULT}

# Architecture Drift 結果
${DRIFT_RESULT}

# Marketing Health 結果
${MARKETING_RESULT}

# Open Loops (High 優先度)
${OPEN_HIGH}

# テンプレート
docs/reports/daily/_template.md の7見出し構造に従って生成してください:
1. 全体要約（3行以内）
2. 今週の変化
3. 進捗（表）
4. Build Failure
5. Architecture Drift 候補
6. マーケ反応
7. 次に見るべき点（3つ）"

# JSON エスケープ
SYSTEM_ESCAPED=$(echo "$SYSTEM_PROMPT" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")
USER_ESCAPED=$(echo "$USER_PROMPT" | python3 -c "import sys,json; print(json.dumps(sys.stdin.read()))")

RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer ${OPENROUTER_API_KEY}" \
  -H "Content-Type: application/json" \
  -H "HTTP-Referer: https://github.com/haruki121731-del/Give-Me-a-DAY-" \
  https://openrouter.ai/api/v1/chat/completions \
  -d "{
    \"model\": \"anthropic/claude-haiku-4-5\",
    \"messages\": [
      {\"role\": \"system\", \"content\": ${SYSTEM_ESCAPED}},
      {\"role\": \"user\", \"content\": ${USER_ESCAPED}}
    ],
    \"max_tokens\": 2000
  }")

# レスポンスからコンテンツを抽出
REPORT_CONTENT=$(echo "$RESPONSE" | python3 -c "
import sys, json
d = json.load(sys.stdin)
if 'choices' in d:
    print(d['choices'][0]['message']['content'])
else:
    print('ERROR: ' + str(d.get('error', d)))
" 2>/dev/null || echo "ERROR: OpenRouter API 呼び出し失敗")

# --- report ファイルを書き出す ---
mkdir -p "$(dirname "${REPORT_PATH}")"
cat > "${REPORT_PATH}" <<REPORTEOF
<!-- generated by scripts/ai/generate_daily_report.sh at ${TIMESTAMP} -->
${REPORT_CONTENT}
REPORTEOF

echo "5. Report written to: ${REPORT_PATH}"
echo ""
echo "=== Done ==="
